### ISSUE TITLE
using metadata from linux doesn't work on mac

### ISSUE THREAD

**Issue by fkowal** [romanowski/hoarder#17]
i've tested your plugin on mac and the metadata from linux didn't work

**Comment by romanowski** [comment]
It seems that this is caused by jvm's jars not being mapped. So it points to `/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/jre/lib/rt.jar` form cache from your machine and `/usr/lib/jvm/java-8-oracle/jre/lib/rt.jar` from mine. 

Wiil add mapper.

**Comment by romanowski** [comment]
Fixed in #32
