### ISSUE TITLE
overrideExistingCache not working

### ISSUE THREAD

**Issue by mfedortsov** [romanowski/hoarder#24]
steps to reproduce:
1. add plugin with default settings to project
2. run sbt
3. sbt:> compile
4. sbt:> stash
5. sbt:> set overrideExistingCache in ThisBuild := true
6. sbt:> stash <-- will cause error

**Comment by romanowski** [comment]
Hmm, there is a  test case for that: https://github.com/romanowski/hoarder/blob/master/0.13/hoarderTests/src/sbt-test/stash/labelsTests/test

Can you retest with newest master build locally? Thanks in advance.

**Comment by mfedortsov** [comment]
For latest version everything is working.
